### ISSUE TITLE
Show error if login is invalid

### ISSUE THREAD

**Issue by rodrigost23** [rodrigost23/LegendasTV-Emby#2]

**Comment by cyberrep** [comment]
Ola Rodrigo, estou com o mesmo problema.

2020-04-04 18:31:42.054 Info App: Searching language: pt-br
2020-04-04 18:31:42.055 Info HttpClient: POST http://legendas.tv/login
2020-04-04 18:31:43.989 Error SubtitleManager: Error downloading subtitles from Legendas TV
	*** Error Report ***
	Version: 4.4.1.0
	Command line: M:\Programas\Emby\system\EmbyServer.dll -noautorunwebapp
	Operating system: Microsoft Windows NT 6.2.9200.0
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Runtime: file:///M:/Programas/Emby/system/System.Private.CoreLib.dll
	System.Environment.Version: 3.1.3
	Processor count: 4
	Program data path: M:\Programas\Emby\programdata
	Application directory: M:\Programas\Emby\system
	System.Collections.Generic.KeyNotFoundException: System.Collections.Generic.KeyNotFoundException: The given key 'Imdb' was not present in the dictionary.
	   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
	   at LegendasTV.LegendasTVProvider.FindIds(SubtitleSearchRequest request, CancellationToken cancellationToken, Int32 depth)+MoveNext()
	   at LegendasTV.LegendasTVProvider.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)
	Source: System.Private.CoreLib
