### ISSUE TITLE
Não consegue mais baixar legenda.

### ISSUE THREAD

**Issue by doutorinfamous** [rodrigost23/LegendasTV-Emby#6]
Olá mestre, até uns 15 dias a legenda tava funcionando e agora não ta mais achando nada.

Será que teve alguma mudança no sistema do LTV?

**Comment by doutorinfamous** [comment]
O erro que aparece no log?

```
2021-06-05 19:08:58.103 Error SubtitleManager: Error downloading subtitles from Legendas TV
	*** Error Report ***
	Version: 4.6.2.0
	Command line: C:\Users\firel\AppData\Roaming\Emby-Server\system\EmbyServer.dll -noautorunwebapp
	Operating system: Microsoft Windows 10.0.19042
	Framework: .NET Core 3.1.13
	OS/Process: x64/x64
	Runtime: C:/Users/firel/AppData/Roaming/Emby-Server/system/System.Private.CoreLib.dll
	Processor count: 16
	Data path: C:\Users\firel\AppData\Roaming\Emby-Server\programdata
	Application path: C:\Users\firel\AppData\Roaming\Emby-Server\system
	System.MissingMethodException: System.MissingMethodException: Method not found: 'System.Collections.Generic.Dictionary`2<System.String,System.String> MediaBrowser.Controller.Entities.BaseItem.get_ProviderIds()'.
	   at LegendasTV.LegendasTVProvider.FindIds(SubtitleSearchRequest request, CancellationToken cancellationToken, Int32 depth)+MoveNext()
	   at LegendasTV.LegendasTVProvider.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Subtitles.SubtitleManager.<>c__DisplayClass17_0.<<SearchSubtitles>b__3>d.MoveNext()
	Source: LegendasTV
	TargetSite: Boolean MoveNext()
```
